# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produits enregistrés'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='generic_name',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(null=True, unique=True, verbose_name='code produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(max_length=1000, null=True, verbose_name="liste d'ingredients"),
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.CharField(max_length=200, null=True, verbose_name='magasins'),
        ),
        migrations.AddField(
            model_name='product',
            name='url_nutrition',
            field=models.CharField(max_length=200, null=True, verbose_name='valeurs nutritionnelles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_picture',
            field=models.CharField(max_length=200, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
