# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('substitute', '0002_auto_20180809_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(max_length=10, null=True, verbose_name='nutriscore'),
        ),
    ]
