# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20180820_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_nutrition',
        ),
    ]
