# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0007_auto_20190207_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='queries',
        ),
        migrations.AddField(
            model_name='query',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='substitute.Product'),
        ),
    ]
